### ISSUE TITLE
5/13-5/17でやること

### ISSUE THREAD

**Issue by 10riridk0** [SoyBeansLab/daizu-online-judge-frontend-old#1]
# UI
- UI/UX検討(※Adobe XDでやりたい)
    - フレームワークを決める
    - 配色
    - フォント
- 画面遷移
    - リンクの検討

# API
- apiから受け取ったjsonファイルの中のどのデータを使うか
- 受け取るデータの名前の検討

# そのた
- 機能の検討(Adminページ, リアタイで更新する系, 解答率, ランキングをグラフで表示など)
- Reactで必要なプラグインの検討
- TypeScriptを導入するかの検討
-  **必要最低限の機能を洗い出して優先度をつける**

**Comment by kurokoji** [comment]
VueではなくてReactでやることにしたんですか?

**Comment by 10riridk0** [comment]
@kurokoji 
React触ってみたかったので今回はReactすることにしました！
