### ISSUE TITLE
タスク振り分け

### ISSUE THREAD

**Issue by 10riridk0** [SoyBeansLab/daizu-online-judge-frontend-old#10]
# しゅり

- [x]   header
- [x]  footer
- [x]  check-box
- [x]  カルーセル(slideshow)

# じゅり

- [x]  button
- [x]  button(textのみ)
- [x]  tabs
- [x]  table
- [ ]  pagination (future)

# くろこじ

- [x]  ソースコードと入出力例を表示するところ
- [ ]  pull down
- [ ]  text-field(source code入力するところ)
- [ ]  text-field(IDとかパスワードを入力するところ)

**Comment by ucpr** [comment]
## 7/1
### しゅり
- footer
### くろこじ
- ソースコードを表示するところ

残りは7/2にみんなでやる
