### ISSUE TITLE
moleculesをつくる

### ISSUE THREAD

**Issue by 10riridk0** [SoyBeansLab/daizu-online-judge-frontend-old#14]
# ページ
## home
- スライドショー
## contests  
- タブたち  
- テーブル  
## contest
- タブ  
- テーブル  
- タイポグラフィ  
## signin/out
- サインアップモーダル  
- サインアウトモーダル  
## problem
- タイポグラフィ(入力例, 出力例など)とコードブロック  
- 問題文の見出しと実行時間制限とメモリ制限  
- 問題文  
- 言語選択のプルダウン  
- テキストフィールドと提出ボタン  
## submit status 
- タイポグラフィ(ソースコード, コンパイルメッセージなど)とコードブロック  
- タイポグラフィ(提出状況)と表  

## 共通部分
- ヘッダー  
- フッター  

# 作業分担
## りし
- [x] home  
- [x] contests  
- [x] contest  

## しゅり  
- [x] signin/out  
- [x] submit status  

## くろこじ
- [x] problem

**Comment by kurokoji** [comment]
ファイル名の命名規則はどうしますか?

**Comment by mosmosyrc** [comment]
そういや結局どうなるんだこれ
脳死で考えたけど「molecure-signup-modal.js」とかどうだろうか。分かりづらいかな
(「app-hogehoge.js」でも良いのかもだけどatomsを作ってるときに使ってたやつだから、間違いを回避するために避けたい気持ち)

**Comment by 10riridk0** [comment]
「app」は再利用可能コンポーネントにつけたいのでやめといたほうがよさそう。

modules-hoge.jsにするよりかは「Home(このコンポーネントを使うページ)-hoge.js」のほうがシンプルでわかりやすいような気がする

**Comment by kurokoji** [comment]
ぶっちゃけコンポーネント名でも良いと思うけどね

**Comment by 10riridk0** [comment]
「ContestTabs.js」的な感じでもふつうにありだと思う🤔まあどのページで使うコンポーネントかがぱっと見でわかったほうがいいっていうなら「Page-hoge.js」だとは思うけど

**Comment by ucpr** [comment]
7/21 までに 終わらせる
