### ISSUE TITLE
molecureの実装について

### ISSUE THREAD

**Issue by ucpr** [SoyBeansLab/daizu-online-judge-frontend-old#195]
atomsでコンポーネントを作ってるけど, molecureで使われていないやつがあるのでそれを直す

**Comment by ucpr** [comment]
#143

**Comment by kurokoji** [comment]
@ucpr 直すってのはどういう意味? 消すってこと?

**Comment by ucpr** [comment]
@kurokoji 修正するが正しいかも！
moleculeのコンポーネントにatomsで作ったやつが使われてないから、それを使って実装するようにしたい

**Comment by ucpr** [comment]
一旦closeするかな
