### ISSUE TITLE
daizu-online-judgeの機能の洗い出し, 優先順位など

### ISSUE THREAD

**Issue by 10riridk0** [SoyBeansLab/daizu-online-judge-frontend-old#2]
# ユーザー側
1. ログイン/ログアウト
1. コンテスト一覧
1. コンテスト詳細
1. 問題一覧
1. 問題文表示
1. ソースコードの提出
1. 自分のソースコードの提出結果一覧
1. 任意のソースコードの提出結果詳細
1. ランキング

# Admin側
1. コンテスト追加・変更
1. 問題の管理
1. ユーザー管理
   ユーザーの削除. 権限の割り振りなど
1. コンテスト参加者全体の提出状況の表示
1. 任意のユーザーの提出状況の表示
1. ~~コンテスト中のランキング~~
   ~~時系列でACの状況がグラフで示されるなど~~

**Comment by ucpr** [comment]
Admin側のとこのコンテスト中のランキングがイメージできてないんだけどどういうやつー？
ユーザー側のランキングとの違いがわからず...><

**Comment by mosmosyrc** [comment]
すまん、Admin側からはランキング見れなくて、ランキングが見れるのはユーザー側だけだったわ
じゅりに報告して訂正するでござ

@10riridk0 いえ～～～～～い見てる～～～～～？？？Admin側からランキングを見ることはできなかったでござ

**Comment by mosmosyrc** [comment]
ユーザー側の機能を先に実装
