### ISSUE TITLE
UIの再検討

### ISSUE THREAD

**Issue by ucpr** [SoyBeansLab/daizu-online-judge-frontend-old#265]
UIの再検討をやっていき :rocket: 

## TODO
- UI検討前にやり直すページとそのページに必要な情報再度洗い出す.

## 関連するやつ
- #52 
- #263 
- #225

**Comment by 10riridk0** [comment]
# home
- ファーストビューはモットー？的なやつ
- 最新コンテスト一覧
- ~~ランキング上位10位~~
- お知らせ
- ~~求人, 検定の内容など~~
- ICT委員会公式Twitterさん

# プロフィール
- 参加したコンテストの一覧
- コンテスト実績(レート, 表なども必要ですか)
- プロフィールの基本設定なども必要？

**Comment by ucpr** [comment]
## Slider
- Sliderで流れているcontestsが開催中か開催予定かわからない

## Contest page
- 参加登録してない場合のページ

## Problemページ
Tabを付けるみたいな話だった気がするけど
https://onlinejudge.u-aizu.ac.jp/courses/lesson/1/ALDS1/1/ALDS1_1_A
のsectionへのaタグみたいなやつのほうが良さそう？

**Comment by ucpr** [comment]
https://www.figma.com/file/dnjlFL0lCuEsxJt76fyd71/daizu-Online-Judge-UI-ver02?node-id=14%3A2
