### ISSUE TITLE
adminページの問題管理まわりについて

### ISSUE THREAD

**Issue by ucpr** [SoyBeansLab/daizu-online-judge-frontend-old#3]
今ucpr.devで動いてるやつの問題追加とかがとてもアレなのでいい感じのやつを考えたい

**Comment by ucpr** [comment]
これadminのページ行って見てもらいたいんだけど、いちいちコピーしてやっていくのがめんどくさい

**Comment by ucpr** [comment]
あと、テストケースの形式とかも

**Comment by mosmosyrc** [comment]
> いちいちコピーして書くのがめんどい

問題の説明やサンプルとかを書くところ？
もしそうなら、コピーとかせずに問題が書かれたファイルをインポートできたらいいなってこと？

**Comment by ucpr** [comment]
そそそ
決められたディレクトリ構成のやつを投げたらいい感じに展開してくれるとか

**Comment by mosmosyrc** [comment]
なるほ
ディレクトリの中身はそれぞれ問題が書かれたファイルがあるのよね？
「どこからどこまでがdescription」「どこからがサンプル」とかがわからないといけないから、短い期間で開発するのを考えると結構辛い気がしている.....
でも確かにあったらめちゃくちゃ便利ではある

**Comment by ucpr** [comment]
description.mdとかsamples/sample1.mdとかで分けたら良いかなと思ってる

**Comment by mosmosyrc** [comment]
ちょっとまってくれよな
problem1/
├ description.md
├ input.md
├ output.md
├ samples/
│　├ sample1.md
│　└ sample2.md
└ hint.md

的な感じの構成をイメージした
使える言語や問題のID, タイトルはページ上で入力させちゃってよい？

**Comment by ucpr** [comment]
言語はページ上でチェックボックスとかでいろいろできたら良さげかなあ
問題ID、タイトルはページ上で入力して良いと思う
