### ISSUE TITLE
apiから受け取ったjsonファイルの中のどのデータを使うか

### ISSUE THREAD

**Issue by ucpr** [SoyBeansLab/daizu-online-judge-frontend-old#4]

**Comment by ucpr** [comment]
これフロントが必要なデータだけを渡すようにするから、各ページでどういうデータがほしいかをまとめてほしい

**Comment by mosmosyrc** [comment]
いつまでにまとまればよさ？？？具体的な日にち教えてほしさ

**Comment by ucpr** [comment]
なるはや、できれば今週中で！
多分デザイン・UI案決まったらまとめられると思うのでそのときにお願いします！

**Comment by ucpr** [comment]
https://github.com/SoyBeansLab/daizu-online-judge-backend/wiki/%E6%AC%B2%E3%81%97%E3%81%84%E3%83%87%E3%83%BC%E3%82%BF%E4%B8%80%E8%A6%A7
